version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP port
      - "9000:9000"   # Native TCP port
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=testdb
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  backend:
    build: ./backend
    container_name: java-backend
    ports:
      - "8123:8123"
    depends_on:
      - clickhouse
    environment:
      - SPRING_DATASOURCE_URL=jdbc:clickhouse://clickhouse:8123/testdb
      - SPRING_DATASOURCE_USERNAME=default
      - SPRING_DATASOURCE_PASSWORD=
    volumes:
      - ./data:/app/data  # optional: mount for CSV files

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  clickhouse_data:
